### ISSUE TITLE
Crash Error on Forge 1.19 In Server 

### ISSUE THREAD

**Issue by DJ1Silva** [PTOM76/UncraftingTable#3]
Hello mod work fine in offline mod but in server mod make server crash with following massage :
Failure message: Uncrafting Table (uncraftingtable76) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

[crash-2022-07-06_18.07.50-fml.txt](https://github.com/PTOM76/UncraftingTable/files/9056858/crash-2022-07-06_18.07.50-fml.txt)

**Comment by PTOM76** [comment]
Both Forge version and Fabric version have been fixed.
Thank you for your report.

**Comment by DJ1Silva** [comment]
> Both Forge version and Fabric version have been fixed. Thank you for your report.

Your Welcome
